### ISSUE TITLE
Handle numbers and booleans

### ISSUE THREAD

**Issue by tilacog** [hay/xml2json#23]
In xml to json conversion, all the values (text) are converted to strings.
It would be nice if numbers and booleans are returned in their own types, as supported by json.

For example:

**_Input (xml)**_

``` xml
    <pi>3.14</pi> 
    <isCool>true</isCool>
```

**_Actual behavior (json output)**_

``` javascript
{
        "pi":"3.14",    // value is a string type
        "isCool":"true" // value is a string type
}
```

**_Proposed behaviour (json output)**_

``` javascript
{
        "pi": 3.14,     // value is a number type
        "isCool": true  // value is a boolean type
}
```

**Comment by mdecaria** [comment]
Hi tilacog

I found this to be an issue aswell.

A quick fix to the problem is to replace this code at the end of the python script. 


    else:
        #print(out)
        import re
        numOut = out.split(' ')

        for place, item in enumerate(numOut):
            if re.match('"\d+"|"\d+.\d+"', item):
                numOut[place] = item.replace('"', "")
        print ' '.join(numOut)


if __name__ == "__main__":
    main()
