### ISSUE TITLE
xml2json method documentation

### ISSUE THREAD

**Issue by kford55** [hay/xml2json#31]
Sorry if this is super elementary, but I'm trying to use the xml2json function, but you only provide an example for json2xml and I have no idea what the options parameter should be when passing it in. Any help would be appreciated.

**Comment by bparruck** [comment]
I have the same issue. It runs fine on the shell, but don't know how to use inside a python program.

**Comment by RebusGlider** [comment]
```
from xmljson import yahoo as yahoo_xml
from xml.etree.ElementTree import `fromstring`
def convert_xml_to_json(xml):
    return dumps(yahoo_xml.data(fromstring(xml)))
```
